"""The Claude Code plugin manifest — the one-install adoption bundle.

`claude-plugin/` packages the three runtime surfaces a Claude Code user installs in
one step — the DOS hooks (`hooks/hooks.json`), the DOS MCP server (`.mcp.json`), and
the generic skill pack (`skills/`) — with a repo-root marketplace catalog
(`.claude-plugin/marketplace.json`) pointing at it. This file pins the contract so
the bundle can't silently drift from the package it fronts:

  * **JSON validity + required fields** — every manifest parses and carries the keys
    the Claude Code plugin/marketplace schema requires (`name`; the marketplace's
    `owner`/`plugins[]`; each plugin's `name`/`source`).
  * **Version lockstep** — the plugin manifest's `version` tracks the package version
    (`dos.__version__`), the same single-source rule the release skill enforces for
    `pyproject.toml` ↔ `__init__.py`. A stale plugin version is the drift this
    catches.
  * **Hooks wire the REAL verbs** — the bundled hooks run the shipped `dos hook
    {pretool,posttool,stop}` verbs (via `python -m dos.cli`, robust against the
    `dos` console script not being on PATH in the host's Python), in the verified
    Claude Code settings shape. These are the same three moments `dos init --hooks`
    wires; the plugin is just the pre-packaged form.
  * **The MCP server is launchable as configured** — the `.mcp.json` command
    (the `dos-mcp` console script, which resolves for both pip and pipx-isolated
    installs) actually imports and builds (the prerequisite the plugin assumes:
    `pip install 'dos-kernel[mcp]'`).
  * **Skills are in sync with source** — the bundled `claude-plugin/skills/` is a
    faithful copy of the single-sourced `src/dos/skills/` (+ the authored
    `dos-setup`), regenerated by `scripts/build_plugin.py`. This calls that
    script's own `--check` logic, so the test and the build agree by construction.
  * **The bundled generic skills still name no host** — the SKP litmus ("a shipped
    generic skill names no host"), re-run on the COPIES, so a copy that somehow
    diverged from the grep-clean source is caught here too.

The plugin lives OUTSIDE the kernel (it consumes `dos`; nothing under `src/dos/`
imports it) — the same one-way arrow as the release scripts and `.claude/` tooling.
"""

from __future__ import annotations

import json
import re
import shutil
import subprocess
import sys
from pathlib import Path

import dos

# scripts/ is not importable as a package; load the build module by path so the
# test and the build share ONE definition of "in sync" (no second copy of the rule).
import importlib.util

_REPO_ROOT = Path(dos.__file__).resolve().parents[2]
_BUILD_PY = _REPO_ROOT / "scripts" / "build_plugin.py"

_spec = importlib.util.spec_from_file_location("_build_plugin", _BUILD_PY)
assert _spec and _spec.loader, f"cannot load {_BUILD_PY}"
build_plugin = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(build_plugin)


PLUGIN_DIR = _REPO_ROOT / "claude-plugin"
PLUGIN_MANIFEST = PLUGIN_DIR / ".claude-plugin" / "plugin.json"
PLUGIN_MCP = PLUGIN_DIR / ".mcp.json"
PLUGIN_HOOKS = PLUGIN_DIR / "hooks" / "hooks.json"
PLUGIN_SKILLS = PLUGIN_DIR / "skills"
MARKETPLACE = _REPO_ROOT / ".claude-plugin" / "marketplace.json"


def _load(path: Path) -> dict:
    return json.loads(path.read_text(encoding="utf-8"))


# ---------------------------------------------------------------------------
# Existence + JSON validity
# ---------------------------------------------------------------------------
def test_all_manifest_files_exist_and_parse():
    for p in (PLUGIN_MANIFEST, PLUGIN_MCP, PLUGIN_HOOKS, MARKETPLACE):
        assert p.is_file(), f"missing manifest: {p}"
        obj = _load(p)  # raises on invalid JSON
        assert isinstance(obj, dict), f"{p} is not a JSON object"


# ---------------------------------------------------------------------------
# plugin.json — required field + version lockstep with the package
# ---------------------------------------------------------------------------
def test_plugin_manifest_required_name():
    manifest = _load(PLUGIN_MANIFEST)
    assert manifest.get("name"), "plugin.json must declare a `name`"
    # kebab-case, the documented plugin-name shape.
    assert re.fullmatch(r"[a-z0-9]+(-[a-z0-9]+)*", manifest["name"]), \
        f"plugin name must be kebab-case: {manifest['name']!r}"


def test_plugin_version_tracks_package_version():
    """The plugin version is single-sourced from the package, like the release skill.

    A bundle fronting `dos-kernel X.Y.Z` should advertise that version; a drifted
    literal here is the staleness this pins. (The bump is part of `/release` — this
    only asserts they match, it doesn't choose the value.)
    """
    manifest = _load(PLUGIN_MANIFEST)
    assert manifest.get("version") == dos.__version__, (
        f"plugin.json version {manifest.get('version')!r} != package "
        f"{dos.__version__!r} — bump claude-plugin/.claude-plugin/plugin.json "
        f"(and the marketplace plugin entry) in lockstep with the release")


# ---------------------------------------------------------------------------
# marketplace.json — schema essentials + it points at the real plugin
# ---------------------------------------------------------------------------
def test_marketplace_required_shape():
    mk = _load(MARKETPLACE)
    assert mk.get("name"), "marketplace must declare a `name`"
    owner = mk.get("owner")
    assert isinstance(owner, dict) and owner.get("name"), \
        "marketplace `owner` must be an object with a `name`"
    plugins = mk.get("plugins")
    assert isinstance(plugins, list) and plugins, \
        "marketplace must list at least one plugin"
    for entry in plugins:
        assert entry.get("name"), "each plugin entry needs a `name`"
        assert entry.get("source"), "each plugin entry needs a `source`"


def test_marketplace_source_resolves_to_the_plugin():
    """The plugin `source` resolves (relative to the marketplace root) to a dir that
    holds a real `.claude-plugin/plugin.json` whose name matches the entry."""
    mk = _load(MARKETPLACE)
    market_root = MARKETPLACE.parent.parent  # the dir CONTAINING .claude-plugin/
    entry = next(e for e in mk["plugins"] if e["name"] == "dos-kernel")
    source = entry["source"]
    assert not source.startswith("../"), "source must not escape the marketplace root"
    resolved = (market_root / source).resolve()
    assert resolved == PLUGIN_DIR.resolve(), \
        f"source {source!r} resolves to {resolved}, expected {PLUGIN_DIR}"
    sub_manifest = _load(resolved / ".claude-plugin" / "plugin.json")
    assert sub_manifest["name"] == entry["name"], \
        "the plugin's own manifest name must match the marketplace entry name"


def test_marketplace_plugin_version_matches_plugin_manifest():
    mk = _load(MARKETPLACE)
    entry = next(e for e in mk["plugins"] if e["name"] == "dos-kernel")
    manifest = _load(PLUGIN_MANIFEST)
    # The entry MAY omit a version (then it inherits the plugin's own); if it
    # declares one, it must agree with the plugin manifest (no split-brain version).
    if "version" in entry:
        assert entry["version"] == manifest["version"], (
            f"marketplace entry version {entry['version']!r} != plugin manifest "
            f"{manifest['version']!r}")


# ---------------------------------------------------------------------------
# hooks.json — wires the REAL shipped verbs, in the CC settings shape
# ---------------------------------------------------------------------------
def _hook_commands(hooks_obj: dict, event: str) -> list[str]:
    cmds: list[str] = []
    for group in hooks_obj.get("hooks", {}).get(event, []):
        for h in group.get("hooks", []):
            c = h.get("command", "")
            if isinstance(c, str):
                cmds.append(c)
    return cmds


def test_hooks_wire_the_dos_verbs():
    hooks = _load(PLUGIN_HOOKS)
    # Each DOS lifecycle moment is wired to its shipped verb. The command runs via
    # `python -m dos.cli` (not the bare `dos` script) so it works even when the
    # console script isn't on the host's PATH. SubagentStop reuses `hook stop`
    # (a subagent's false "done" is verified the same way the main agent's is);
    # UserPromptSubmit resets the wait-marker budget on each new human prompt;
    # SessionStart injects the ground-truth orientation digest.
    expected = {
        "PreToolUse": "hook pretool",
        "PostToolUse": "hook posttool",
        "Stop": "hook stop",
        "SubagentStop": "hook stop",
        "UserPromptSubmit": "hook marker",
        "SessionStart": "hook session-start",
    }
    for event, verb in expected.items():
        cmds = _hook_commands(hooks, event)
        assert cmds, f"no hook wired for {event}"
        assert any(("dos.cli " + verb) in c or ("dos " + verb) in c for c in cmds), \
            f"{event} does not run `{verb}`: {cmds}"
        # The entries carry the CC `type: command` shape.
        for group in hooks["hooks"][event]:
            for h in group["hooks"]:
                assert h.get("type") == "command", \
                    f"{event} hook entry must be type=command: {h}"


def test_stopfailure_notifier_and_heal_are_wired():
    """The API-failure notifier + breaker-heal are actually wired (not just shipped).

    A StopFailure hook's output and exit code are IGNORED by the harness, so it
    can never re-launch a stopped session — the harness's own retry
    (CLAUDE_CODE_MAX_RETRIES / CLAUDE_CODE_RETRY_WATCHDOG) resumes a transient
    wall. This pins the HONEST binding: a StopFailure hook scoped to the
    transient-wall error classes that runs `hook stop-failure` to record +
    attribute + escalate, and a Stop-event heal running the same verb with
    `--success` so the breaker resets after a clean session.

    The hook must NOT claim to rewake: asyncRewake on a StopFailure is a no-op
    (the exit code it waits on is discarded), so it must be absent — keeping it
    would advertise a resumption the contract cannot deliver.
    """
    hooks = _load(PLUGIN_HOOKS)
    sf_groups = hooks["hooks"].get("StopFailure", [])
    sf_hooks = [h for g in sf_groups for h in g.get("hooks", [])]
    assert sf_hooks, "no StopFailure hook wired — the API-failure notifier is dead"
    # Honest contract: NO asyncRewake (it cannot rewake — exit code is ignored).
    assert all(h.get("asyncRewake") is not True for h in sf_hooks), \
        "StopFailure must NOT set asyncRewake — its exit code is ignored, so it " \
        "cannot rewake; advertising it promises a resumption the contract can't keep"
    # Scoped to the transient-wall error classes via the event matcher.
    assert any("overloaded" in (g.get("matcher", "") or "") for g in sf_groups), \
        "StopFailure should match the transient-wall classes (e.g. overloaded)"
    assert any("hook stop-failure" in h.get("command", "")
               and "--success" not in h.get("command", "") for h in sf_hooks), \
        "StopFailure must run `hook stop-failure` (the record/attribute/escalate path)"
    # Stop → the heal (so the breaker doesn't open from stale failures).
    stop_cmds = _hook_commands(hooks, "Stop")
    assert any("hook stop-failure" in c and "--success" in c for c in stop_cmds), \
        "Stop must also run `hook stop-failure --success` to heal the breaker"


def test_windows_lifecycle_hooks_use_powershell_syntax():
    hooks = _load(PLUGIN_HOOKS)["hooks"]
    for event in ("SessionStart", "UserPromptSubmit"):
        command = hooks[event][0]["hooks"][0]["commandWindows"]
        assert "if /i" not in command
        assert "||" not in command
        assert "exit /b" not in command
        assert "$LASTEXITCODE" in command
        assert "2>$null" in command
        assert command.endswith("exit 0")


def test_hook_commands_are_cold_safe_for_codex_plugin_shell(tmp_path):
    """The plugin may be loaded by Codex, where `CLAUDE_PLUGIN_ROOT` is absent and
    the hook shell can be WSL bash with no `python` on PATH. In that shape the
    SessionStart hook used to exit non-zero before the agent saw the first turn.

    Pin both halves: the command carries the Codex/Windows fallbacks, and on a
    POSIX bash with an empty PATH every bundled hook command exits 0 and emits
    nothing instead of failing the session.
    """
    import os
    import pytest

    hooks = _load(PLUGIN_HOOKS)
    all_cmds = [
        h["command"]
        for groups in hooks["hooks"].values()
        for group in groups
        for h in group.get("hooks", [])
        if isinstance(h.get("command"), str)
    ]
    assert all_cmds
    session_cmd = _hook_commands(hooks, "SessionStart")[0]
    assert "CODEX_PLUGIN_ROOT" in session_cmd
    assert "powershell.exe" in session_cmd
    assert session_cmd.endswith("|| true")

    if os.name == "nt":
        pytest.skip("the executable empty-PATH check is POSIX-bash only")
    bash = shutil.which("bash")
    if not bash:
        pytest.skip("bash not available")

    env = {
        "PATH": str(tmp_path),
        "HOME": str(tmp_path),
        "CLAUDE_PLUGIN_ROOT": "",
        "CODEX_PLUGIN_ROOT": "",
    }
    for cmd in all_cmds:
        proc = subprocess.run(
            [bash, "-lc", cmd],
            cwd=tmp_path,
            input="{}",
            capture_output=True,
            text=True,
            env=env,
        )
        assert proc.returncode == 0, f"hook command is not fail-safe: {cmd}\n{proc.stderr}"
        assert proc.stdout == ""
        assert proc.stderr == ""


def test_hook_verbs_are_real_cli_subcommands():
    """Guard against a typo'd verb: each wired `hook <verb>` is a real `dos` command.

    Runs `python -m dos.cli hook <verb> --help` and asserts it isn't an
    argparse 'invalid choice' error. (The hooks themselves read stdin; --help is the
    safe way to confirm the subcommand EXISTS without feeding it an event.)
    """
    import os
    env = {**os.environ, "PYTHONPATH": str(_REPO_ROOT / "src")}
    for verb in ("pretool", "posttool", "stop", "marker", "session-start"):
        proc = subprocess.run(
            [sys.executable, "-m", "dos.cli", "hook", verb, "--help"],
            capture_output=True, text=True, env=env,
        )
        assert proc.returncode == 0, (
            f"`dos hook {verb} --help` failed (rc={proc.returncode}): "
            f"{proc.stderr or proc.stdout}")

# ---------------------------------------------------------------------------
# .mcp.json — the server it names actually builds
# ---------------------------------------------------------------------------
def test_mcp_server_config_shape():
    mcp = _load(PLUGIN_MCP)
    servers = mcp.get("mcpServers")
    assert isinstance(servers, dict) and servers, ".mcp.json needs `mcpServers`"
    assert "dos" in servers, "the DOS server must be registered under `dos`"
    dos_server = servers["dos"]
    assert dos_server.get("command"), "the server entry needs a `command`"
    args = dos_server.get("args", [])
    # The launcher must front the shipped MCP server one of two equivalent ways:
    #   * the `dos-mcp` console script (preferred — it carries its own interpreter
    #     via shebang, so it resolves for pip AND pipx-isolated installs; a bare
    #     `python -m dos_mcp.server` can't see the module when it lives in a pipx
    #     venv off the host interpreter), or
    #   * an explicit `python -m dos_mcp.server`.
    # Bare `python` as the command is NOT safe on hosts that ship only `python3`
    # (e.g. macOS) — it ENOENTs. Unlike the hooks, the MCP spec has no shell-fallback
    # chain, so the single command must self-resolve; the console script does.
    blob = str(dos_server.get("command", "")) + " " + " ".join(str(a) for a in args)
    assert "dos-mcp" in blob or "dos_mcp.server" in blob, \
        f"server should launch the `dos-mcp` console script or `dos_mcp.server`: {dos_server}"


def test_mcp_server_actually_builds():
    """The prerequisite the plugin assumes: the MCP server imports + constructs.

    This is the same surface `tests/test_mcp_server.py` exercises; here it confirms
    the package the plugin's `.mcp.json` will launch is importable when the `[mcp]`
    extra is present, so the bundle isn't fronting a broken command.

    The `[mcp]` extra is optional (the kernel's own dependency set is PyYAML-only),
    so this SKIPS when `mcp` is absent — matching `tests/test_mcp_server.py`'s
    `importorskip`. Without the guard the test fails in a `[dev]`-only env on the
    server's own graceful install-hint `SystemExit`, which is correct behaviour, not
    a regression.
    """
    import pytest
    pytest.importorskip("mcp", reason="dos-mcp needs the optional `mcp` extra")
    from dos_mcp.server import build_server
    server = build_server()
    assert server is not None


# ---------------------------------------------------------------------------
# skills/ — in sync with source, and still host-free
# ---------------------------------------------------------------------------
def test_bundled_skills_in_sync_with_source():
    """The plugin's skills are a faithful copy of src/dos/skills/ (+ dos-setup).

    Delegates to the build script's own drift check, so the test and the generator
    can never disagree about what "in sync" means. If this fails, run:
        python scripts/build_plugin.py
    """
    findings = build_plugin.check(_REPO_ROOT)
    assert not findings, (
        "claude-plugin/skills/ is out of sync with src/dos/skills/:\n  "
        + "\n  ".join(findings)
        + "\nrun: python scripts/build_plugin.py")


# ---------------------------------------------------------------------------
# bin/ launchers — REACHABLE, not merely present (present != reached)
# ---------------------------------------------------------------------------
def test_every_tracked_launcher_is_reachable_or_allowlisted():
    """A launcher shipped + tracked but invoked by no hook is dead code that LOOKS
    live. `test_hook_binaries_bundled.test_launchers_are_tracked` proves PRESENCE;
    this proves REACHABILITY — every tracked bin/ launcher is either referenced by
    a hooks.json command or on the manual-integration allowlist (the docs/204 §3
    presence-not-goal wall, turned inward on the plugin's own packaging).

    Regression target: dos-hook.ps1 shipped with a comment claiming hooks.json
    invoked it, but the bundle's hooks are `shell: bash` → the POSIX launcher, so
    the .ps1 was never reached. It is now allowlisted as a manual helper.
    """
    findings = build_plugin.check_launcher_reachability(_REPO_ROOT)
    assert not findings, (
        "a bundled launcher is tracked but no hook reaches it:\n  "
        + "\n  ".join(findings))


def test_reachability_check_actually_bites():
    """Guard the guard: prove the reachability check is not vacuous. With an empty
    allowlist, the unwired dos-hook.ps1 MUST be flagged — otherwise the check would
    silently pass on a future genuinely-orphaned launcher too."""
    import unittest.mock
    with unittest.mock.patch.object(build_plugin, "_MANUAL_LAUNCHERS", frozenset()):
        findings = build_plugin.check_launcher_reachability(_REPO_ROOT)
    assert any("dos-hook.ps1" in f for f in findings), (
        "with no allowlist the .ps1 should be flagged unreachable — the check is "
        f"blind if it is not. findings: {findings}")


def test_ps1_comment_does_not_claim_it_is_wired():
    """The .ps1 once falsely claimed 'hooks.json invokes this'. A manual-helper
    launcher must say so, not advertise itself as wired — the comment is the thing a
    future reader trusts."""
    ps1 = (PLUGIN_DIR / "bin" / "dos-hook.ps1").read_text(encoding="utf-8")
    assert "NOT wired by the bundled hooks.json" in ps1, \
        "dos-hook.ps1 must state it is not wired by the bundle (it's a manual helper)"
    assert "hooks.json invokes this" not in ps1, \
        "dos-hook.ps1 must not claim hooks.json invokes it (it does not)"


def test_bundled_skill_frontmatter_is_valid_yaml():
    """Every bundled skill's YAML frontmatter PARSES and carries name + description.

    A skill whose frontmatter fails to parse loads at runtime with EMPTY metadata —
    Claude Code silently drops every field (name, description, the trigger), so the
    skill is un-invokable and `claude plugin validate ./claude-plugin` errors. The
    classic break is a `: ` (colon-space) in an *unquoted* description scalar within
    the first 1024 chars, which a spec-compliant YAML parser reads as a mapping key
    (the dos-skillify regression this guards). Checks the bundled copies — the bytes
    that actually ship — with the same YAML parse the host validator performs.
    """
    import yaml  # the kernel's one runtime dependency; always present
    fm_re = re.compile(r"^---\n(.*?)\n---\n", re.S)
    for skill_md in sorted(PLUGIN_SKILLS.rglob("SKILL.md")):
        rel = skill_md.relative_to(_REPO_ROOT)
        text = skill_md.read_text(encoding="utf-8")
        m = fm_re.match(text)
        assert m, f"{rel} has no leading `---` YAML frontmatter block"
        try:
            meta = yaml.safe_load(m.group(1))
        except yaml.YAMLError as e:
            raise AssertionError(
                f"{rel} frontmatter is not valid YAML — it loads with EMPTY metadata "
                f"at runtime (all fields dropped) and fails `claude plugin validate`. "
                f"A `: ` in an unquoted description is the usual cause; quote it or use "
                f"an em-dash. Parser said: {e}") from e
        assert isinstance(meta, dict), f"{rel} frontmatter must be a YAML mapping"
        for key in ("name", "description"):
            val = meta.get(key)
            assert isinstance(val, str) and val.strip(), \
                f"{rel} frontmatter is missing a non-empty `{key}`"


def test_bundled_skills_include_generic_pack_and_setup():
    found = {p.parent.name for p in PLUGIN_SKILLS.rglob("SKILL.md")}
    # Every generic-pack skill is bundled...
    src_skills = {d.name for d in (Path(dos.__file__).parent / "skills").iterdir()
                  if d.is_dir() and (d / "SKILL.md").is_file()}
    assert src_skills <= found, f"missing generic skills in plugin: {src_skills - found}"
    # ...plus the plugin-only skills the build authors: dos-setup (onboarding) and
    # dos-stats (surface the bundled dos-hook binary's observation log, docs/276).
    for plugin_skill in ("dos-setup", "dos-stats"):
        assert plugin_skill in found, f"the {plugin_skill} plugin skill must be bundled"


# The job literals the SKP design law forbids in a SHIPPED generic skill (the same
# set tests/test_skill_pack_generic.py greps for) — re-checked on the COPIES.
_FORBIDDEN_HOST_LITERALS = [
    r"docs/_plans",
    r"output/next-up",
    r"docs/dispatch:",
    r"\bapply\b",
    r"\btailor\b",
    r"\bdiscovery\b",
]


# The plugin-only skills the build AUTHORS (not generic-pack copies). They
# legitimately name the plugin's own surfaces — the `dos-kernel` pip package, the
# bundled `dos-hook` binary, `${CLAUDE_PLUGIN_ROOT}` — so the generic "names no host"
# litmus does not apply to them, the same way the driver layer is exempt from
# "kernel imports no host". Keep this in lockstep with build_plugin's `written` set.
_PLUGIN_ONLY_SKILLS = {"dos-setup", "dos-stats"}


def test_bundled_generic_skills_name_no_host():
    """The 'a shipped generic skill names no host' litmus, run on the bundled copies.

    The plugin-only authored skills (`_PLUGIN_ONLY_SKILLS`: dos-setup, dos-stats) are
    EXEMPT: they are not generic SKP screenplays — they name the plugin's own surfaces
    (the `dos-kernel` pip package, the bundled `dos-hook stats` verb) on purpose, so
    the no-host rule doesn't apply to them.
    """
    for skill_md in PLUGIN_SKILLS.rglob("SKILL.md"):
        if skill_md.parent.name in _PLUGIN_ONLY_SKILLS:
            continue
        text = skill_md.read_text(encoding="utf-8")
        for pat in _FORBIDDEN_HOST_LITERALS:
            assert not re.search(pat, text), (
                f"{skill_md.relative_to(_REPO_ROOT)} names a host literal "
                f"/{pat}/ — a shipped generic skill must name no host")
