package hook

import (
	"bufio"
	"encoding/json"
	"os"
	"path/filepath"
	"testing"
	"time"
)

// parityCase mirrors one line of parity/corpus.jsonl — the hermetic differential
// case generated by gen_corpus.py against the LIVE Python decider. The Go test
// replays each case through the native decider with the SAME injected inputs and
// asserts byte-equality on `ExpectedStdout` (the GHF3 byte-exact gate) AND tag
// equality on `Decision` (the decision projection).
type parityCase struct {
	Name           string           `json:"name"`
	Event          map[string]any   `json:"event"`
	Leases         []map[string]any `json:"leases"`
	RuntimeFiles   []string         `json:"runtime_files"`
	ExpectedStdout string           `json:"expected_stdout"`
	Decision       string           `json:"decision"`
	// docs/355 — the interactive-operator session class the Python oracle stamped
	// into the corpus (gen_corpus.py emits `operator_session: true` for the no-loop
	// human cases). The harness MUST inject it as `in.OperatorSession`, or the Go
	// decider runs as a loop session and hard-denies where Python now WARNs — a
	// false byte drift.
	OperatorSession bool `json:"operator_session"`
	// Now + Override carry the docs/296 override-arm cases hermetically: the Python
	// oracle injected these same facts + clock (never a live arm file), so the Go
	// replay must inject them too. Absent on every non-override case (nil/"" ⇒ the
	// disarmed default: in.OverrideFacts nil, in.Now zero — byte-unchanged).
	Now      string          `json:"now"`
	Override *corpusOverride `json:"override"`
}

// corpusOverride is the JSON shape of a corpus line's injected armed window — the
// hermetic twin of the arm file `ReadOverride` would parse, fed straight into
// OverrideFacts so the test never touches disk.
type corpusOverride struct {
	Until  string   `json:"until"`
	Reason string   `json:"reason"`
	Scope  []string `json:"scope"`
}

func loadCorpus(t *testing.T) []parityCase {
	t.Helper()
	path := filepath.Join("parity", "corpus.jsonl")
	f, err := os.Open(path)
	if err != nil {
		t.Fatalf("open corpus %s: %v (run `python go/internal/hook/parity/gen_corpus.py > %s`)", path, err, path)
	}
	defer f.Close()
	var cases []parityCase
	sc := bufio.NewScanner(f)
	sc.Buffer(make([]byte, 1<<20), 1<<20)
	for sc.Scan() {
		line := sc.Bytes()
		if len(line) == 0 {
			continue
		}
		var c parityCase
		if err := json.Unmarshal(line, &c); err != nil {
			t.Fatalf("corpus line unmarshal: %v", err)
		}
		cases = append(cases, c)
	}
	if err := sc.Err(); err != nil {
		t.Fatalf("corpus scan: %v", err)
	}
	if len(cases) == 0 {
		t.Fatal("corpus is empty")
	}
	return cases
}

// leasesFromCorpus converts the injected lease dicts to the internal lease shape
// the same way replayJournal surfaces them (lane + tree).
func leasesFromCorpus(raw []map[string]any) []lease {
	out := make([]lease, 0, len(raw))
	for _, m := range raw {
		out = append(out, lease{lane: asStr(m["lane"]), tree: asStrSlice(m["tree"])})
	}
	return out
}

// overrideFromCorpus builds the injected OverrideFacts + clock for an override-case
// line, or (nil, zero) when the line carries no `override` block (the disarmed
// default). The scope entries are normalized EXACTLY as `ReadOverride` stores them
// (`normOverridePath`), and `until`/`now` parse with the corpus's offset spelling, so
// the hermetic replay sees byte-identical facts to what the Python oracle disposed.
func overrideFromCorpus(t *testing.T, c parityCase) (*OverrideFacts, time.Time) {
	t.Helper()
	if c.Override == nil {
		return nil, time.Time{}
	}
	until := coerceUntil(c.Override.Until)
	if until.IsZero() {
		t.Fatalf("corpus %q: unparseable override.until %q", c.Name, c.Override.Until)
	}
	now := coerceUntil(c.Now)
	if now.IsZero() {
		t.Fatalf("corpus %q: unparseable now %q", c.Name, c.Now)
	}
	var scope []string
	for _, s := range c.Override.Scope {
		if s != "" {
			scope = append(scope, normOverridePath(s))
		}
	}
	return &OverrideFacts{Until: until, Reason: c.Override.Reason, Scope: scope}, now
}

// TestParityCorpus is the differential parity gate (GHF3). For every corpus case
// it injects the SAME leases + runtime files the Python oracle saw, runs the
// native decider, and asserts the emitted bytes are IDENTICAL to the Python
// decider's. A decision drift fails here loudly; this is the CI ratchet.
func TestParityCorpus(t *testing.T) {
	cases := loadCorpus(t)
	for _, c := range cases {
		c := c
		t.Run(c.Name, func(t *testing.T) {
			ev := parseEvent(c.Event)
			in := Inputs{
				LiveLeases:      leasesFromCorpus(c.Leases),
				RuntimeFiles:    c.RuntimeFiles,
				OperatorSession: c.OperatorSession,
			}
			if facts, now := overrideFromCorpus(t, c); facts != nil {
				in.OverrideFacts = facts
				in.Now = now
			}
			d := Decide(ev, in)
			got := d.Render()
			if got != c.ExpectedStdout {
				t.Fatalf("BYTE DRIFT on %q:\n  py: %q\n  go: %q", c.Name, c.ExpectedStdout, got)
			}
			if d.DecisionTag != c.Decision {
				t.Fatalf("DECISION DRIFT on %q: py=%q go=%q", c.Name, c.Decision, d.DecisionTag)
			}
		})
	}
}

// TestParityNegativeProseOnly proves the gate excludes nothing it should not: two
// events whose decision is identical but whose REASON differs only in prose must
// both be denies (the decision projection is the gated thing). We construct a
// deny whose reason prose differs from the corpus's and confirm the DECISION tag
// is still "deny" — i.e. a prose-only difference does not change the verdict.
// (The full prose-vs-decision split is the docs/124 §2 contract; here the hook's
// reason is pure int/enum/path prose, so the whole line is byte-gated, but this
// pins that the TAG is what a consumer keys on.)
func TestParityNegativeProseOnly(t *testing.T) {
	// Same self-modify decision, two different lane names -> different reason prose,
	// same deny tag.
	e1 := eventFor("Edit", "/work/workspace", map[string]any{"file_path": "src/dos/arbiter.py"})
	e2 := eventFor("Write", "/work/workspace", map[string]any{"file_path": "src/dos/arbiter.py"})
	d1 := Decide(e1, Inputs{RuntimeFiles: dispatchRuntimeFiles})
	d2 := Decide(e2, Inputs{RuntimeFiles: dispatchRuntimeFiles})
	if d1.DecisionTag != "deny" || d2.DecisionTag != "deny" {
		t.Fatalf("both should deny: %q %q", d1.DecisionTag, d2.DecisionTag)
	}
	if d1.Render() == d2.Render() {
		t.Fatal("expected prose to differ between Edit and Write lane names")
	}
}
